### ISSUE TITLE
VRC.UI.Elements.Menus not found

### ISSUE THREAD

**Issue by louisa-uno** [RemiLuvle/Hellsing#2]
In the QMNestedButtons.cs one the `Object.DestroyImmediate(MenuObject.GetComponent<VRC.UI.Elements.Menus.LaunchPadQMMenu>());` doesn't work because the import of VRC.UI.Elements.Menus doesn't work.

**Comment by ghost** [comment]
hes not updating it to the new menu

**Comment by louisa-uno** [comment]
Alright
